<a href="https://colab.research.google.com/github/Sampath2000/python-projects/blob/main/salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Salary Prediction by Decisiontree classifier**

---



 Data set link :-[here](https://drive.google.com/file/d/1AzfFm2N2118sqNibVZq9VQkkoidlhOZW/view?usp=sharing)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
from sklearn import metrics

In [80]:
from google.colab import files
uploaded=files.upload()

Saving salary_prediction.csv to salary_prediction.csv


In [81]:
df=pd.read_csv('salary_prediction.csv')

In [82]:
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [83]:
df.shape

(16, 4)

In [84]:
df.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [85]:
df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 640.0+ bytes


In [87]:
print(df.company.value_counts())
print(df.job.value_counts())
print(df.degree.value_counts())

google        6
facebook      6
abc pharma    4
Name: company, dtype: int64
business manager       6
sales executive        5
computer programmer    5
Name: job, dtype: int64
bachelors    8
masters      8
Name: degree, dtype: int64


In [88]:
df.replace({'company':{'google':0,'facebook':1,'abc pharma':2}},inplace=True)
df.replace({'job':{'business manager':0,'sales executive':1,'computer programmer':2}},inplace=True)
df.replace({'degree':{'bachelors':0,'masters':1,}},inplace=True)

In [89]:
df

company  job  degree  salary_more_then_100k
0         0    1       0                      0
1         0    1       1                      0
2         0    0       0                      1
3         0    0       1                      1
4         0    2       0                      0
5         0    2       1                      1
6         2    1       1                      0
7         2    2       0                      0
8         2    0       0                      0
9         2    0       1                      1
10        1    1       0                      1
11        1    1       1                      1
12        1    0       0                      1
13        1    0       1                      1
14        1    2       0                      1
15        1    2       1                      1

In [90]:
df.tail(3)

company  job  degree  salary_more_then_100k
13        1    0       1                      1
14        1    2       0                      1
15        1    2       1                      1

In [91]:
x=df.drop(['salary_more_then_100k'],axis=1)
y=df['salary_more_then_100k']

In [92]:
print(x)

    company  job  degree
0         0    1       0
1         0    1       1
2         0    0       0
3         0    0       1
4         0    2       0
5         0    2       1
6         2    1       1
7         2    2       0
8         2    0       0
9         2    0       1
10        1    1       0
11        1    1       1
12        1    0       0
13        1    0       1
14        1    2       0
15        1    2       1


In [93]:
print(y)

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64


In [94]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [95]:
print(X_test)
print("-------------------------------------")
print(Y_test)

    company  job  degree
12        1    0       0
4         0    2       0
5         0    2       1
0         0    1       0
-------------------------------------
12    1
4     0
5     1
0     0
Name: salary_more_then_100k, dtype: int64


In [96]:
decision_tree=DecisionTreeClassifier()
decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [97]:
y_predicted=decision_tree.predict(X_train)
print(y_predicted)

[1 1 0 1 0 1 1 1 0 1 1 0]


In [98]:
print(Y_train.values)

[1 1 0 1 0 1 1 1 0 1 1 0]


In [99]:
y_predicted_test=decision_tree.predict(X_test)
print(y_predicted_test)

[1 0 0 0]


In [100]:
print(Y_test.values)

[1 0 1 0]


In [102]:
accuracy_score=metrics.accuracy_score(y_predicted_test,Y_test)
print(accuracy_score)

0.75


In [103]:
a=decision_tree.predict([[2,1,0]])
print(a)

[0]


In [104]:
a=decision_tree.predict([[0,1,0]])
print(a)

[0]
